[package]
name = "support"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2.0.1" , features = ["serde"] } 
iso_currency = { version ="0.5.3", features = ["with-serde"]}
serde = { version = "1.0.219" , features = ["derive"] }
serde_json = "1.0.141"